### ISSUE TITLE
Question to onebone

### ISSUE THREAD

**Issue by Arkdevnoder** [onebone/MineCombat-Nukkit#4]
$xcos = cos(($player->yaw + 90)/180 \* M_PI);     $zcos = sin(($player->yaw + 90)/180 \* M_PI);  
         $pcos = cos(($player->pitch + 90)/180 \* M_PI);  
         $x_ = $player->getX(); 
        $y_ = $player->getY();  
         $z_ = $player->getZ();  
         for($o_=0; $o_<100;$o_++){  
         $x = $x_ + ($o_ \* $xcos);  
        $y = $y_ + ($o_ \* $pcos);  
        $z = $z_ + ($o_ \* $zcos);       

How to check attack of player? Sorry i know, it is pocketmine

**Comment by onebone** [comment]
I have checked players around ($x, $y, $z).
